### ISSUE TITLE
Private key included in source control

### ISSUE THREAD

**Issue by SteffeyDev** [Xicronic/poosdsmallproj#1]
Hello, fellow classmate here, also one of the Hack@UCF members, just noticed that you included your SSH private key in your source control, along with instructions on how to access the server.  Because this is a public repo, that means anyone can log in to your server and do whatever they would like with it.  It won't be too long before someone else finds this and starts mining cryptocurrency on the server (there are bots online looking for things like this).  I would recommend removing this key from your Github repo and revoking it immediately, and then generating a new key and distributing it to your team using a non-public means.

**Comment by Waddlen** [comment]
Thanks,

The server has been terminated so the KP is now useless. In the future we'll avoid this.
